name: howler
description: Audio library for the modern web. This makes working with audio in Dart easy and reliable across many platforms. (Port of howler.js to Dart)
version: 1.0.3
homepage: https://github.com/gmpassos/howler.dart
author: Graciliano M. Passos <gracilianomp@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
 swiss_knife: 
  git: 
    url: https://github.com/blacksaltIT/swiss_knife
    ref: 4fc2d9f68904a04b776b8e0ef94c66e38066685c


dev_dependencies:
  test: ^1.5.1
